version: '3'
services:
  # update containers automatically
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30 --cleanup
    restart: always
  # main application
  app:
    build:
      context: backend/
    depends_on:
      - postgres
    volumes:
    - ./backend/logs/:/app/logs
    # NOTE: используйте volume mount для подключения папки скриптов для оркестрации
    - ./scripts/:/scripts:ro
    # Сюда уйдет collected_static после ./manage.py collectstatic
    - collected_static:/app/collected_static:rw
    # Секреты приложения
    - ./backend/setting_additions.py:/app/setting_additions.py:ro
    restart: always
    entrypoint: ["/scripts/wait-for-it.sh", "postgres:5432", "--", "/app/entrypoint.sh"]

  # database
  postgres:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: postgres
    expose:
      - 5432
    ports:
    - 54325:5432
    volumes:
    - ./postgres/sql:/docker-entrypoint-initdb.d:ro
    - pg_data:/var/lib/postgresql
    restart: always

  # static files
  nginx:
    build:
      context: frontend/
    depends_on:
      - app
    ports:
      - 80:80
    volumes:
    # NOTE: collected_static генерится на бекенде (ну вот так, да)
    # пока что передаем в nginx через volume mount
    - collected_static:/app/collected_static
    - ./frontend/logs:/var/log/nginx/:rw
    restart: always

  # backups with rotation
  database_backup_service:
    image: prodrigestivill/postgres-backup-local
    restart: always
    volumes:
      - ./postgres/db_backups:/backups
    links:
      - postgres
    depends_on:
      - postgres
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=drec_stud_site
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      # - POSTGRES_EXTRA_OPTS=-Z6 --schema=public --blobs
      - SCHEDULE=@daily
      - BACKUP_KEEP_DAYS=7
      # - BACKUP_KEEP_WEEKS=4
      # - BACKUP_KEEP_MONTHS=6
      - HEALTHCHECK_PORT=8080

  # Offline passwords storage
  redis:
    image: redis:6
    volumes:
    - redis_data:/data
    ports:
    - 6379:6379
    expose:
      - 6379
    restart: always

  # VK bot
  vk_bot:
    build:
      context: vk_bot/
    depends_on:
      - postgres
      - redis
    volumes:
      # NOTE: используйте volume mount для подключения папки скриптов для оркестрации
    - ./scripts:/scripts:ro
    - ./vk_bot/logs:/app/logs:rw
    # Секреты приложения
    - ./vk_bot/.env:/app/.env:ro
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=drec_stud_site
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: always
    entrypoint: ["/scripts/wait-for-it.sh", "redis:6379", "--", "/app/entrypoint.sh"]

  # return money for unavailable machines
  money_return_service:
    build:
      context: money_return/
    depends_on:
      - postgres
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_DB: drec_stud_site
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      # NOTE: используйте volume mount для подключения папки скриптов для оркестрации
    - ./scripts:/scripts:ro
    entrypoint: ["/scripts/wait-for-it.sh", "postgres:5432", "--", "/app/entrypoint.sh"]

  lockbox_health_check_service:
    build:
      context: lockbox_health_check/
    volumes:
      - ./lockbox_health_check/logs:/app/logs:rw

volumes:
  pg_data:
  redis_data:
  collected_static: