# Generated by Django 2.2.13 on 2021-09-13 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0029_auto_20210825_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='group_number',
            field=models.CharField(max_length=15, verbose_name='Номер группы'),
        ),
        migrations.AlterField(
            model_name='user',
            name='room_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Номер комнаты'),
        ),
    ]
